In [10]:
import pandas as pd
import tensorflow as tf
import matplotlib.pyplot as plt
import numpy as np

In [11]:
#import dataset
df = pd.read_csv('response indo.csv')
df

,Age (umur),Occupation (Pekerjaan),Music,Slow songs or fast songs,Dance,Folk,Country,Classical music,Musical,Pop,...,"Reggae, Ska","Swing, Jazz",Rock n roll,Alternative,Latino,"Techno, Trance",Opera,Smoking,Alcohol,Healthy eating
0,19,Mahasiswa,3,3,1,1,1,1,4,5,...,1,4,1,1,1,1,1,never smoked,never,2
1,19,Mahasiswa,5,3,5,4,4,4,5,4,...,4,5,5,5,4,5,4,current smoker,never,2
2,20,Mahasiswa,5,2,1,2,1,5,5,4,...,1,3,1,1,1,1,3,never smoked,social drinker,5
3,19,Mahasiswa,5,2,3,3,4,4,4,4,...,2,5,3,3,4,3,3,never smoked,never,4
4,19,Mahasiswa,5,3,4,4,3,3,3,4,...,3,4,3,3,3,3,3,never smoked,never,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,20,Mahasiswa,5,3,4,3,4,2,3,4,...,1,3,3,2,1,1,2,never smoked,social drinker,3
71,20,Mahasiswa,5,3,2,2,3,2,3,5,...,3,4,3,3,4,4,4,never smoked,never,3
72,20,Mahasiswa,4,4,2,1,1,3,2,4,...,1,5,1,2,1,5,1,never smoked,social drinker,4
73,21,Mahasiswa,5,3,5,3,3,3,3,4,...,3,3,3,5,2,4,2,never smoked,social drinker,1
74,19,Mahasiswa,5,3,4,2,2,3,3,4,...,1,2,3,4,1,2,2,never smoked,social drinker,3

In [12]:
#mengubah string menjadi angka di Smoking  
df["Smoking"] = df["Smoking"].replace('current smoker', 3)  
df["Smoking"] = df["Smoking"].replace('former smoker', 2) 
df["Smoking"] = df["Smoking"].replace('tried smoking', 1)   
df["Smoking"] = df["Smoking"].replace('never smoked', 0)
#mengubah string menjadi angka di Alcohol
df["Alcohol"] = df["Alcohol"].replace('drink a lot', 2)  
df["Alcohol"] = df["Alcohol"].replace('social drinker', 1)    
df["Alcohol"] = df["Alcohol"].replace('never', 0)

In [13]:
#drop data
newDf = df.dropna()
print(newDf.isna().values.any())

False

In [14]:
#declare feature dan target
feature = newDf[["Music","Slow songs or fast songs","Dance","Folk","Country","Classical music","Musical","Pop","Rock","Metal or Hardrock","Punk","Hiphop, Rap","Reggae, Ska","Swing, Jazz","Rock n roll","Alternative","Latino","Techno, Trance","Opera"]]
target = newDf[["Smoking","Alcohol","Healthy eating"]]

In [17]:
from sklearn.linear_model import LinearRegression
x, y = np.array(feature), np.array(target)

In [18]:
#mengapply linear regression dan fit
model = LinearRegression().fit(x, y)

In [19]:
r_sq = model.score(x, y)
print('coefficient of determination:', r_sq)# hasil R-Squared (bila di bawah 0.5 maka feature tidak berpengaruh kepada target)
print('intercept:', model.intercept_)# hasil coefficient pada b0 (bila di atas 0.05 maka feature tidak berpengaruh kepada target)
print('slope:', model.coef_)# hasil coefficient pada bias setelah b0 yakni b1 b2 b3(bila di atas 0.05 maka feature tidak berpengaruh kepada target)

coefficient of determination: 0.25462993810589
intercept: [-0.1049353   0.54798976  1.34878076]
slope: [[-0.24203701  0.06666012 -0.12241315  0.07216439  0.02871775  0.10085446
   0.00277247  0.02422173  0.0569197   0.05889235 -0.04694674  0.10073666
   0.05387589  0.0129651   0.10599831  0.15403392 -0.16766027 -0.02788561
   0.01928874]
 [ 0.16250622 -0.07199688 -0.11183086 -0.09898572 -0.11816168 -0.11821318
   0.07680708 -0.04414884  0.14604851 -0.28906435  0.12289637 -0.01709104
   0.00860719  0.02349297  0.14939571  0.02346773 -0.03480531  0.04671162
   0.02467975]
 [ 0.48056602  0.26237031 -0.136246    0.01755553 -0.11414822 -0.10770069
   0.30511918 -0.016153   -0.27238222  0.08162894  0.04657326 -0.04724924
  -0.14124375  0.02503882  0.11084119 -0.08993002  0.06844524  0.05423198
  -0.16320764]]

C:\Users\Albert\Anaconda3\lib\site-packages\sklearn\base.py:420: FutureWarning: The default value of multioutput (not exposed in score method) will change from 'variance_weighted' to 'uniform_average' in 0.23 to keep consistent with 'metrics.r2_score'. To specify the default value manually and avoid the warning, please either call 'metrics.r2_score' directly or make a custom scorer with 'metrics.make_scorer' (the built-in scorer 'r2' uses multioutput='uniform_average').
  "multioutput='uniform_average').", FutureWarning)

In [20]:
y_pred = model.predict(x)
print('predicted response:', y_pred, sep='\n')
#menghasilkan prediksi prediksi target dengan linear regression

predicted response:
[[ 2.41779359e-01  6.82355450e-01  3.98287740e+00]
 [ 9.33022576e-01  3.51691465e-01  3.05446790e+00]
 [-1.31419440e-01  7.05621864e-01  4.37995773e+00]
 [-1.00978695e-02  4.05921268e-01  3.61093552e+00]
 [ 2.52141850e-01  2.65384622e-01  3.24518802e+00]
 [ 1.00035320e-01  3.94205951e-01  3.04517255e+00]
 [ 1.46223517e-01  4.28305066e-01  1.71289046e+00]
 [-9.92335506e-02  6.02963637e-01  3.45901826e+00]
 [ 1.56706835e-01  5.85068369e-01  2.59545903e+00]
 [ 3.68103525e-01  1.02473776e+00  3.15402330e+00]
 [-5.88063212e-02  3.01401966e-01  4.00975578e+00]
 [ 1.46788435e-03  4.85286809e-01  3.95590818e+00]
 [-2.96205762e-01  5.74392348e-01  3.40314063e+00]
 [ 1.74963314e-01  5.80924857e-01  2.80126297e+00]
 [ 3.76373719e-01  2.91042875e-01  3.04980674e+00]
 [ 4.44023743e-01  4.42314868e-01  3.62675111e+00]
 [ 6.36648569e-01  2.70430722e-01  2.66781270e+00]
 [ 7.52659692e-01  7.64470849e-01  2.53365761e+00]
 [ 7.44977396e-02  6.81705689e-01  4.18331260e+00]
 [ 3.39923812e-02  3.23024289e-01  2.91497642e+00]
 [ 4.47125523e-01  1.02812319e-02  2.63934386e+00]
 [ 5.23158044e-01  9.67723504e-01  2.87539661e+00]
 [ 2.12910584e-01  4.25650433e-01  3.36993590e+00]
 [ 5.03081357e-01  1.54954075e-01  2.33535016e+00]
 [ 8.03614032e-01  8.75054356e-01  3.22110137e+00]
 [ 6.73641530e-02  2.64041114e-01  3.75952751e+00]
 [ 2.28624644e-01  7.06048705e-01  4.13173209e+00]
 [ 3.12091962e-01  1.98545494e-01  2.62965642e+00]
 [ 1.18225303e-01  9.87796102e-01  3.85475799e+00]
 [ 3.00456317e-01  2.44094760e-01  2.54539022e+00]
 [ 2.44178523e-01  1.95675518e-01  3.45370686e+00]
 [ 1.08886248e-01 -6.36837403e-03  3.40904636e+00]
 [ 1.94028484e-01  5.30659624e-01  3.35393286e+00]
 [ 7.98974632e-02  3.93493404e-01  3.85335293e+00]
 [ 7.18139750e-01  7.47170760e-01  3.20527847e+00]
 [ 1.75375679e-01  3.05765921e-01  3.72296382e+00]
 [ 4.54807470e-01  4.53076897e-01  3.13052960e+00]
 [-1.00978645e-01  1.27587471e-01  3.52757326e+00]
 [-3.56537204e-01  4.09637373e-01  3.85059814e+00]
 [-7.97930293e-02  4.47912177e-01  3.78204760e+00]
 [ 9.63898487e-03  8.50487526e-01  4.05177273e+00]
 [ 4.53129355e-01  1.13094260e+00  2.78990520e+00]
 [ 6.18830046e-01  4.88566976e-01  3.19799694e+00]
 [ 2.20281784e-01  5.38072642e-01  3.10631000e+00]
 [ 1.43878862e+00  4.19077970e-01  2.98804285e+00]
 [ 2.97990716e-01  2.34726314e-01  2.80428849e+00]
 [ 4.17166573e-01  3.18273174e-01  2.78394620e+00]
 [-8.73981363e-02  3.74255149e-01  2.77453873e+00]
 [ 9.19641775e-01  2.36925045e-01  2.61690604e+00]
 [-1.05792047e-01  3.00918957e-01  3.33041534e+00]
 [-1.01737785e-01  1.00997487e+00  3.92700532e+00]
 [ 1.13584881e+00  7.80882740e-01  2.92374252e+00]
 [ 1.39225768e-01  1.20542952e-01  2.17677771e+00]
 [ 7.31304704e-02  4.70510296e-01  3.53441331e+00]
 [ 8.86259923e-01  5.87178305e-01  2.98534500e+00]
 [ 1.41699705e-01  1.86843506e-01  3.71933157e+00]
 [ 9.08394468e-01  6.76591547e-01  3.16525229e+00]
 [ 2.48087921e-01  6.44473939e-01  3.35251909e+00]
 [ 2.28699180e-02 -6.78312217e-02  3.08692123e+00]
 [ 7.28761321e-01  5.70567330e-01  3.06791901e+00]
 [ 2.46612611e-01  5.30351906e-01  3.42772043e+00]
 [ 5.19555588e-01  3.98904569e-01  3.51425978e+00]
 [ 4.31173550e-01  3.37563209e-01  3.47639096e+00]
 [ 7.86002879e-01  4.99592756e-01  2.73811984e+00]
 [ 6.31897382e-01  1.14375549e+00  3.37312466e+00]
 [ 3.18817353e-01  3.83385337e-01  2.90799201e+00]
 [ 4.92904395e-01  2.33155895e-01  2.80129847e+00]
 [ 6.32799513e-01  5.01261847e-01  2.96375065e+00]
 [ 1.24014142e+00  1.27485993e+00  3.02166030e+00]
 [ 2.08138864e-01  1.91918757e-01  3.24853755e+00]
 [ 1.34055031e-01  7.06986691e-01  3.27658572e+00]
 [ 1.24797843e-01  9.40688292e-01  3.16427320e+00]
 [-7.39021573e-02  7.46271066e-01  3.80148324e+00]
 [ 3.55368286e-01  9.10947851e-01  2.87222414e+00]
 [ 5.35285514e-01  7.28324516e-01  2.99163252e+00]]